In [1]:
# Required Imports
import subprocess
from pathlib import Path
import parser
from tabulate_molecules import (
    create_results_table_water,
    create_results_table_ethanol,
    create_results_table_methane,
    create_results_table_formaldehyde,
    create_results_table_hcn
)

In [2]:
# Configuration required for GAMESS
GAMESS_DIR = Path(r"C:\Users\Public\gamess-64")
OUTPUT_DIR = Path(r"D:\Quantum Computing\CDAC Internship 2026\Python GAMESS DFT Jupyter\GAMESS Output Files")
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
RUNGMS = GAMESS_DIR / "rungms.bat"
GAMESS_VERSION = "2023.R1.intel"
NCORES = "1"

In [3]:
# Water
water_SVWN = "water_SVWN_LDA_631Gdp"
water_PBE = "water_PBE_GGA_631Gdp"
water_revTPSS = "water_revTPSS_metaGGA_631Gdp"
water_B3LYP = "water_B3LYP_hybridGGA_631Gdp"
water_M06 = "water_M06_hybridMetaGGA_631Gdp"


# Ethanol
ethanol_SVWN = "ethanol_SVWN_LDA_631Gdp"
ethanol_PBE = "ethanol_PBE_GGA_631Gdp"
ethanol_revTPSS = "ethanol_revTPSS_metaGGA_631Gdp"
ethanol_B3LYP = "ethanol_B3LYP_hybridGGA_631Gdp"
ethanol_M06 = "ethanol_M06_hybridMetaGGA_631Gdp"


# Methane
methane_SVWN = "methane_SVWN_LDA_631Gdp"
methane_PBE = "methane_PBE_GGA_631Gdp"
methane_revTPSS = "methane_revTPSS_metaGGA_631Gdp"
methane_B3LYP = "methane_B3LYP_hybridGGA_631Gdp"
methane_M06 = "methane_M06_hybridMetaGGA_631Gdp"


# Formaldehyde
formaldehyde_SVWN = "formaldehyde_SVWN_LDA_631Gdp"
formaldehyde_PBE = "formaldehyde_PBE_GGA_631Gdp"
formaldehyde_revTPSS = "formaldehyde_revTPSS_metaGGA_631Gdp"
formaldehyde_B3LYP = "formaldehyde_B3LYP_hybridGGA_631Gdp"
formaldehyde_M06 = "formaldehyde_M06_hybridMetaGGA_631Gdp"


# Hydrogen Cyanide
hcn_SVWN = "hcn_SVWN_LDA_631Gdp"
hcn_PBE = "hcn_PBE_GGA_631Gdp"
hcn_revTPSS = "hcn_revTPSS_metaGGA_631Gdp"
hcn_B3LYP = "hcn_B3LYP_hybridGGA_631Gdp"
hcn_M06 = "hcn_M06_hybridMetaGGA_631Gdp"

In [4]:
# Function to run the GAMESS input files as jobs
def run_gamess(job_name):

    result = subprocess.run(
        [
            str(GAMESS_DIR / "rungms.bat"),
            job_name,
            "2023.R1.intel",
            "1"
        ],
        cwd=GAMESS_DIR,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        check=True
    )

    output_text = result.stdout.replace("\r", "\n")

    # Save GAMESS output as TXT files
    output_file = OUTPUT_DIR / f"{job_name}.txt"
    output_file.write_text(
        output_text,
        encoding="utf-8"
    )

    return output_text

In [5]:
# Calling all GAMESS jobs

# Water
run_gamess(water_SVWN)
run_gamess(water_PBE)
run_gamess(water_revTPSS)
run_gamess(water_B3LYP)
run_gamess(water_M06)

# Ethanol
run_gamess(ethanol_SVWN)
run_gamess(ethanol_PBE)
run_gamess(ethanol_revTPSS)
run_gamess(ethanol_B3LYP)
run_gamess(ethanol_M06)

# Methane
run_gamess(methane_SVWN)
run_gamess(methane_PBE)
run_gamess(methane_revTPSS)
run_gamess(methane_B3LYP)
run_gamess(methane_M06)

# Formaldehyde
run_gamess(formaldehyde_SVWN)
run_gamess(formaldehyde_PBE)
run_gamess(formaldehyde_revTPSS)
run_gamess(formaldehyde_B3LYP)
run_gamess(formaldehyde_M06)

# Hydrogen Cyanide
run_gamess(hcn_SVWN)
run_gamess(hcn_PBE)
run_gamess(hcn_revTPSS)
run_gamess(hcn_B3LYP)
run_gamess(hcn_M06);

In [6]:
# Calling parser function to retrieve useful data as JSON files

# Water
parser.parse_gamess(water_SVWN)
parser.parse_gamess(water_PBE)
parser.parse_gamess(water_revTPSS)
parser.parse_gamess(water_B3LYP)
parser.parse_gamess(water_M06)

# Ethanol
parser.parse_gamess(ethanol_SVWN)
parser.parse_gamess(ethanol_PBE)
parser.parse_gamess(ethanol_revTPSS)
parser.parse_gamess(ethanol_B3LYP)
parser.parse_gamess(ethanol_M06)

# Methane
parser.parse_gamess(methane_SVWN)
parser.parse_gamess(methane_PBE)
parser.parse_gamess(methane_revTPSS)
parser.parse_gamess(methane_B3LYP)
parser.parse_gamess(methane_M06)

# Formaldehyde
parser.parse_gamess(formaldehyde_SVWN)
parser.parse_gamess(formaldehyde_PBE)
parser.parse_gamess(formaldehyde_revTPSS)
parser.parse_gamess(formaldehyde_B3LYP)
parser.parse_gamess(formaldehyde_M06)

# Hydrogen Cyanide
parser.parse_gamess(hcn_SVWN)
parser.parse_gamess(hcn_PBE)
parser.parse_gamess(hcn_revTPSS)
parser.parse_gamess(hcn_B3LYP)
parser.parse_gamess(hcn_M06);

In [7]:
# Tabulate the parsed data

df_water = create_results_table_water()
df_water

,Job,Method,Basis,SCF Converged,SCF Iterations,Total Energy (Hartree),Nuclear Repulsion (Hartree),Exchange-Correlation (Hartree),Electron Number
0,water_B3LYP_hybridGGA_631Gdp,B3LYP,"6-61G(d,p)",True,15,-76.382488,9.189534,-7.529789,10.0
1,water_M06_hybridMetaGGA_631Gdp,M06,"6-61G(d,p)",True,16,-76.385869,9.189534,-6.908843,10.0
2,water_PBE_GGA_631Gdp,PBE,"6-61G(d,p)",True,15,-76.332785,9.189534,-9.265551,10.0
3,water_revTPSS_metaGGA_631Gdp,REVTPSS,"6-61G(d,p)",True,15,-76.461726,9.189534,-9.404545,10.0
4,water_SVWN_LDA_631Gdp,SVWN,"6-61G(d,p)",True,15,-75.854679,9.189534,-8.773627,10.0

In [8]:
df_ethanol = create_results_table_ethanol()
df_ethanol

,Job,Method,Basis,SCF Converged,SCF Iterations,Total Energy (Hartree),Nuclear Repulsion (Hartree),Exchange-Correlation (Hartree),Electron Number
0,ethanol_B3LYP_hybridGGA_631Gdp,B3LYP,"6-61G(d,p)",True,18,-154.948258,82.010751,-17.472718,25.999943
1,ethanol_M06_hybridMetaGGA_631Gdp,M06,"6-61G(d,p)",True,19,-154.938726,82.010751,-16.004257,25.999994
2,ethanol_PBE_GGA_631Gdp,PBE,"6-61G(d,p)",True,18,-154.839772,82.010751,-21.494274,25.999941
3,ethanol_revTPSS_metaGGA_631Gdp,REVTPSS,"6-61G(d,p)",True,19,-155.147628,82.010751,-21.838523,25.999995
4,ethanol_SVWN_LDA_631Gdp,SVWN,"6-61G(d,p)",True,18,-153.729267,82.010751,-20.328260,25.999937

In [9]:
df_methane = create_results_table_methane()
df_methane

,Job,Method,Basis,SCF Converged,SCF Iterations,Total Energy (Hartree),Nuclear Repulsion (Hartree),Exchange-Correlation (Hartree),Electron Number
0,methane_B3LYP_hybridGGA_631Gdp,B3LYP,"6-61G(d,p)",True,14,-40.488037,13.472036,-5.560739,10.000469
1,methane_M06_hybridMetaGGA_631Gdp,M06,"6-61G(d,p)",True,15,-40.479086,13.472036,-5.088585,10.000031
2,methane_PBE_GGA_631Gdp,PBE,"6-61G(d,p)",True,14,-40.449689,13.472036,-6.835075,10.000480
3,methane_revTPSS_metaGGA_631Gdp,REVTPSS,"6-61G(d,p)",True,14,-40.553348,13.472036,-6.952598,10.000030
4,methane_SVWN_LDA_631Gdp,SVWN,"6-61G(d,p)",True,15,-40.102273,13.472036,-6.463659,10.000503

In [10]:
df_hcn = create_results_table_hcn()
df_hcn

,Job,Method,Basis,SCF Converged,SCF Iterations,Total Energy (Hartree),Nuclear Repulsion (Hartree),Exchange-Correlation (Hartree),Electron Number
0,hcn_B3LYP_hybridGGA_631Gdp,B3LYP,"6-61G(d,p)",True,17,-93.372848,23.878822,-10.137255,14.0
1,hcn_M06_hybridMetaGGA_631Gdp,M06,"6-61G(d,p)",True,19,-93.359848,23.878822,-9.279376,14.0
2,hcn_PBE_GGA_631Gdp,PBE,"6-61G(d,p)",True,18,-93.309086,23.878822,-12.478423,14.0
3,hcn_revTPSS_metaGGA_631Gdp,REVTPSS,"6-61G(d,p)",True,18,-93.484128,23.878822,-12.670160,14.0
4,hcn_SVWN_LDA_631Gdp,SVWN,"6-61G(d,p)",True,17,-92.611884,23.878822,-11.753733,14.0

In [11]:
df_formald = create_results_table_formaldehyde()
df_formald

,Job,Method,Basis,SCF Converged,SCF Iterations,Total Energy (Hartree),Nuclear Repulsion (Hartree),Exchange-Correlation (Hartree),Electron Number
0,formaldehyde_B3LYP_hybridGGA_631Gdp,B3LYP,"6-61G(d,p)",True,17,-114.443889,31.255737,-11.829652,16.000036
1,formaldehyde_M06_hybridMetaGGA_631Gdp,M06,"6-61G(d,p)",True,20,-114.437331,31.255737,-10.838578,15.999999
2,formaldehyde_PBE_GGA_631Gdp,PBE,"6-61G(d,p)",True,18,-114.369508,31.255737,-14.556685,16.000037
3,formaldehyde_revTPSS_metaGGA_631Gdp,REVTPSS,"6-61G(d,p)",True,19,-114.576583,31.255737,-14.785365,15.999999
4,formaldehyde_SVWN_LDA_631Gdp,SVWN,"6-61G(d,p)",True,19,-113.587572,31.255737,-13.743020,16.000038